backend:
  name: github
  repo: SnowRainyl/SnowRainyl.github.io
  branch: main
  base_url: https://snowrainyl.snowflow062.workers.dev

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: post_zh
    label: "中文文章"
    folder: content/zh/posts
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "标题", name: title, widget: string }
      - { label: "发布时间", name: date, widget: datetime }
      - label: "分类"
        name: categories
        widget: select
        required: false
        multiple: false
        options:
          - { label: "技术探索", value: "技术探索" }
          - { label: "读书笔记", value: "读书笔记" }
          - { label: "生活随笔", value: "生活随笔" }
      - { label: "标签", name: tags, widget: list, required: false }
      - { label: "正文", name: body, widget: markdown }

  - name: post_en
    label: "English Posts"
    folder: content/en/posts
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Date", name: date, widget: datetime }
      - label: "Category"
        name: categories
        widget: select
        required: false
        multiple: false
        options:
          - { label: "Tech & Projects", value: "Tech & Projects" }
          - { label: "Book Notes", value: "Book Notes" }
          - { label: "Life & Travel", value: "Life & Travel" }
      - { label: "Tags", name: tags, widget: list, required: false }
      - { label: "Body", name: body, widget: markdown }
